-- 车模星球 Products 种子数据
-- 生成时间: 2026-04-25
-- 来源: 星仔的1:64市场行情研究报告

-- Hot Wheels 产品 (brand_id=1)
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('95 Mazda RX-7', 'Hot Wheels', '$uper TH', '1:64', '全新', '合金', 45, 45, 'SH4R5N', 'Mazda', 'RX-7', 'JDM', '普款', 0, 90, 45, 300, 600, '上涨', 19, 145, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Honda Civic EF $uper TH', 'Hot Wheels', '$uper TH', '1:64', '全新', '合金', 59, 59, 'SHF5R5N', 'Honda', 'Civic EF', 'JDM', '超稀有', 1, 180, 59, 200, 500, '上涨', 20, 150, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Porsche 911 GT3 RS RLC', 'Hot Wheels', 'RLC', '1:64', '全新', '合金', 280, 280, 'R5LC5R5N', 'Porsche', '911 GT3 RS', '跑车', '神物', 1, 560, 280, 400, 800, '上涨', 21, 155, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Nissan Skyline GT-R R34 $uper', 'Hot Wheels', '$uper TH', '1:64', '全新', '合金', 49, 49, 'SHGTR5N', 'Nissan', 'Skyline GT-R R34', 'JDM', '超稀有', 1, 196, 49, 250, 550, '稳定', 22, 160, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Toyota Land Cruiser 40 Premium', 'Hot Wheels', 'Premium', '1:64', '全新', '合金', 79, 79, 'SHLCT5N', 'Toyota', 'Land Cruiser 40', '越野', '稀有', 0, 158, 79, 150, 300, '稳定', 23, 165, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('McLaren F1 GTR $uper TH', 'Hot Wheels', '$uper TH', '1:64', '全新', '合金', 49, 49, 'SHMLRN5N', 'McLaren', 'F1 GTR', '赛车', '超稀有', 1, 196, 49, 200, 450, '上涨', 24, 170, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('32 Ford Deuce Roadster RLC', 'Hot Wheels', 'RLC', '1:64', '全新', '合金', 320, 320, 'R5LCF5RN', 'Ford', 'Deuce Roadster', '经典', '神物', 1, 640, 320, 300, 600, '稳定', 25, 175, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Datsun 510 Wagon RLC', 'Hot Wheels', 'RLC', '1:64', '全新', '合金', 300, 300, 'R5LC51N', 'Datsun', '510 Wagon', 'JDM', '神物', 1, 600, 300, 350, 700, '上涨', 26, 180, 0, datetime('now'));

-- Tomica 产品 (brand_id=2)
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Nissan Skyline GT-R R34 Z-Tune TLV-NEO', 'Tomica', 'TLV-NEO', '1:64', '全新', '合金', 199, 199, 'TLV-NS34ZT', 'Nissan', 'Skyline GT-R R34', 'JDM', '神物', 1, 398, 199, 299, 599, '上涨', 27, 185, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Toyota 2000GT TLV', 'Tomica', 'TLV', '1:64', '全新', '合金', 169, 169, 'TLV-T2GT', 'Toyota', '2000GT', '经典', '超稀有', 1, 338, 169, 249, 499, '稳定', 28, 190, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Mazda Savanna RX-7 FC3S TLV-NEO', 'Tomica', 'TLV-NEO', '1:64', '全新', '合金', 159, 159, 'TLV-MRFCS', 'Mazda', 'Savanna RX-7 FC3S', 'JDM', '超稀有', 1, 318, 159, 199, 399, '上涨', 29, 195, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Porsche 911 Turbo 930 TLV', 'Tomica', 'TLV', '1:64', '全新', '合金', 179, 179, 'TLV-P931T', 'Porsche', '911 Turbo 930', '跑车', '超稀有', 1, 358, 179, 299, 549, '稳定', 30, 200, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Lamborghini Countach 25th TLV-NEO', 'Tomica', 'TLV-NEO', '1:64', '全新', '合金', 199, 199, 'TLV-LCNT25', 'Lamborghini', 'Countach 25th', '超跑', '神物', 1, 398, 199, 349, 699, '上涨', 31, 205, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Toyota Corolla Levin AE86 TLV', 'Tomica', 'TLV', '1:64', '全新', '合金', 169, 169, 'TLV-AE86', 'Toyota', 'Corolla Levin AE86', 'JDM', '超稀有', 1, 338, 169, 199, 449, '上涨', 32, 210, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Subaru Impreza WRX STI 22B TLV', 'Tomica', 'TLV', '1:64', '全新', '合金', 179, 179, 'TLV-SUB22B', 'Subaru', 'Impreza WRX STI 22B', 'JDM', '超稀有', 1, 358, 179, 249, 499, '上涨', 33, 215, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Mazda Roadster Miata NA TLV', 'Tomica', 'TLV', '1:64', '全新', '合金', 129, 129, 'TLV-MRDSTR', 'Mazda', 'Roadster Miata NA', '跑车', '稀有', 1, 258, 129, 149, 299, '稳定', 34, 220, 0, datetime('now'));

-- Matchbox 产品 (brand_id=3)
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('London Double-Decker Bus', 'Matchbox', 'Moving Parts', '1:64', '全新', '合金', 39, 39, 'MB-MK01', 'Leyland', 'London Bus', '巴士', '稀有', 0, 78, 39, 89, 199, '稳定', 35, 225, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Superfast 金色系列 1970s', 'Matchbox', 'Superfast', '1:64', '全新', '合金', 120, 120, 'MB-SF70GL', 'Various', 'Superfast Gold', '经典', '神物', 1, 240, 120, 199, 499, '上涨', 36, 230, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('消防车限量版', 'Matchbox', "Collector's", '1:64', '全新', '合金', 69, 69, 'MB-FIRE01', 'Various', 'Fire Engine', '特种', '超稀有', 1, 138, 69, 129, 299, '稳定', 37, 235, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Mercedes-Benz联名系列', 'Matchbox', 'MBX Pro', '1:64', '全新', '合金', 79, 79, 'MB-MB001', 'Mercedes-Benz', 'AMG GT', '跑车', '稀有', 0, 158, 79, 89, 179, '稳定', 38, 240, 0, datetime('now'));

-- MINI GT 产品 (brand_id=4)
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Nissan GT-R R35 Liberty Walk', 'MINI GT', 'Liberty Walk', '1:64', '全新', '合金', 99, 99, 'MGT-R35LB', 'Nissan', 'GT-R R35', 'JDM', '稀有', 0, 198, 99, 109, 169, '稳定', 39, 245, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Porsche 911 GT3 RS Kaido House', 'MINI GT', 'Kaido House', '1:64', '全新', '合金', 119, 119, 'MGT-GT3KH', 'Porsche', '911 GT3 RS', '跑车', '超稀有', 1, 238, 119, 129, 199, '上涨', 40, 250, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Toyota Supra MK4 Liberty Walk', 'MINI GT', 'Liberty Walk', '1:64', '全新', '合金', 99, 99, 'MGT-SUPRA4', 'Toyota', 'Supra MK4', 'JDM', '稀有', 0, 198, 99, 109, 159, '稳定', 41, 255, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Honda NSX NA2 Mugen', 'MINI GT', 'Mugen', '1:64', '全新', '合金', 129, 129, 'MGT-NSXMGN', 'Honda', 'NSX NA2', 'JDM', '超稀有', 1, 258, 129, 139, 229, '上涨', 42, 260, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('BMW M3 E46 GTR Kanno', 'MINI GT', 'Kanno', '1:64', '全新', '合金', 119, 119, 'MGT-M3GTR', 'BMW', 'M3 E46 GTR', '赛车', '超稀有', 1, 238, 119, 129, 209, '稳定', 43, 265, 0, datetime('now'));

-- Tarmac Works 产品 (brand_id=5)
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Porsche 911 GT3 RS', 'Tarmac Works', 'GT Series', '1:64', '全新', '合金', 89, 89, 'TW-GT3RS', 'Porsche', '911 GT3 RS', '赛车', '稀有', 0, 178, 89, 99, 149, '稳定', 44, 270, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Nissan GT-R R35 GT500', 'Tarmac Works', 'GT Series', '1:64', '全新', '合金', 99, 99, 'TW-GTR500', 'Nissan', 'GT-R GT500', '赛车', '超稀有', 1, 198, 99, 119, 199, '上涨', 45, 275, 0, datetime('now'));
INSERT INTO products (name, brand, series, scale, condition, material, price, original_price, model_code, make, model, category, rarity, is_limited, collector_value, msrp, market_price_low, market_price_high, price_trend, likes, views, is_sold, posted_at) VALUES ('Toyota GR86 赛车版', 'Tarmac Works', 'GT Series', '1:64', '全新', '合金', 79, 79, 'TW-GR86R', 'Toyota', 'GR86', '赛车', '稀有', 0, 158, 79, 89, 139, '稳定', 46, 280, 0, datetime('now'));
